apiVersion: v1
kind: Service
metadata:
  name: fleetman-queue

spec:
  selector:
    app: queue
    release: "1"
  
  ports:
    - name: queue
      port: 8161
      nodePort: 30011

    - name: endpoint
      port: 61616

  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-webapp

spec:
  selector:
    app: webapp
    
  
  ports:
    - name: http
      port: 80
      nodePort: 30056
  type: NodePort
